### ISSUE TITLE
All minecraft:player.something have default value of true 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [SirLich/bedrock-schema-docs#9]
All the minecraft:players components default value is 'true' even though the type is a float 

This effects
minecraft:player.exhaustion
minecraft:player.experience
minecraft:player.level
minecraft:player.saturation

https://unreal.codes/2022/10/12/chrome_390LPwS51P.png

**Comment by SirLich** [comment]
Wow, very true. Thanks for the bug report. At the outset, I'm not sure whether this is an issue inside of the Schemas, or inside of my script. Maybe I'm accidentally treating a '1' as truthy, and somehow accidentally casting it to a 'true'.

Although to be honest, I would more suspect the base schemas.
